table _Medidas
	lineageTag: 4e7aa8a2-de6b-454d-9dba-65b44934c06d

	measure 'Total de Lojas Ativas' = CALCULATE(DISTINCTCOUNT(dimLoja[LOJA]), dimLoja[ATIVO])
		formatString: 0
		displayFolder: Geral
		lineageTag: bb575c41-2a1b-47a5-952d-376ccfacd87f

	measure 'Data do último serviço' = COALESCE(CALCULATE(MAX('fatTarefa'[dtConclusao]), 'fatTarefa'[Date]<>BLANK()),"-")
		formatString: Short Date
		displayFolder: Serviços
		lineageTag: 625a96cd-3252-459b-825f-826c7d33da45

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Último Serviço' = COALESCE(CALCULATE(MAX('fatTarefa'[fase_nome]), FILTER('fatTarefa', 'fatTarefa'[dtConclusao] = [Data do último serviço])),"-")
		displayFolder: Serviços
		lineageTag: bad3107a-246d-4ee6-a263-b46f6743582d

	measure 'Qtd. Atendimentos TXT' =
			
			
			VAR Qtd_Tarefas = CALCULATE(COUNT('fatTarefa'[id]), 'fatTarefa'[dtConclusao] <> BLANK())
			
			RETURN IF(ISBLANK(Qtd_Tarefas), "-", Qtd_Tarefas)
		formatString: 0
		displayFolder: Serviços
		lineageTag: f1c77b91-3b39-42f9-84cb-3f40a76f7441

	measure Associado =
			
			
			VAR NLojas = COUNT(dimLoja[LOJA])
			
			RETURN IF(NLojas>1, "-", MIN(dimLoja[RESPONSAVEL]))
		displayFolder: Sobre a Loja
		lineageTag: 34bd90d2-0013-4c11-a5f4-5ed5197ae3d2

	measure 'Qtd. Cidades' = DISTINCTCOUNT(dimCidades[Name])
		formatString: 0
		displayFolder: Geral
		lineageTag: 930dbc8c-fc1b-47bc-87a8-8da748b71d33

	measure 'Lojas Ativas' = ```
			
			CALCULATE (
			    COUNTROWS (dimLoja),
			    FILTER (
			        dimLoja,
			        dimLoja[DATA_ASSOCIACAO] <= MAX('dimCalendario SULTS'[Date]) &&
			        (ISBLANK(dimLoja[DATA_DESASSOCIACAO]) || dimLoja[DATA_DESASSOCIACAO] >= MIN('dimCalendario SULTS'[Date]))
			    )
			)
			
			```
		formatString: 0
		displayFolder: Geral
		lineageTag: e94cb9df-c79a-4095-98a6-b498d8dac9f3

	measure 'Realizam algum serviço' =
			
			
			VAR QtdTarefas = COUNT(fatTarefa[id])
			
			RETURN COALESCE(
			    CALCULATE(
			        DISTINCTCOUNT(fatTarefa[projeto_id]),
			        FILTER(
			            fatTarefa,
			            QtdTarefas>=1
			        )
			    ),"-")
		formatString: 0
		displayFolder: Geral
		lineageTag: afceda12-6258-4f22-bb35-6a7d494421ad

	measure 'Qtd Filiais' = CALCULATE(COUNT(dimLoja[FILIAL]), dimLoja[FILIAL] = "S")
		formatString: 0
		displayFolder: Geral
		lineageTag: fda23c57-19be-422c-acd7-f4c8a6efe665

	measure 'Qtd. Atendimentos' = ```
			
			        COALESCE(
			            CALCULATE(
			                DISTINCTCOUNT(fatTarefa[id]), 
			                fatTarefa[nome] <> "CADUCIDADE", 
			                fatTarefa[nome] <> "TENTATIVA"),
			            0
			        )
			```
		formatString: 0
		displayFolder: Serviços
		lineageTag: 97f5de5f-1a8f-4988-b5ca-2aa5f299a0e7

	measure 'Qtd. Lojas' = DISTINCTCOUNT(fatTarefa[LOJA])
		formatString: 0
		displayFolder: Serviços
		lineageTag: a1bedb0e-ca5a-4886-9e83-50d1e6dd2959

	measure 'Média de Atendimentos por Loja' = DIVIDE([Qtd. Atendimentos], [Qtd. Lojas],0)
		formatString: 0.0
		displayFolder: Serviços
		lineageTag: 40d55c86-4bb6-4b44-9091-77263c9814b3

	measure 'Média de atendimentos' = COALESCE(DIVIDE([Qtd. Atendimentos],[Qtd. Dias],0),0)
		formatString: 0.0
		displayFolder: Serviços
		lineageTag: 25c86faf-15b4-45ea-b967-11d2e8ddb84b

	measure 'Média de Atendimentos por Responsável' = COALESCE(DIVIDE([Qtd. Atendimentos],[Qtd. Responsaveis], 0),0)
		formatString: 0.0
		displayFolder: Serviços
		lineageTag: f20914c2-fe9d-4d2b-ad6f-d4e3eae81415

	measure 'Atendido BALCONISTA' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "BALCONISTA"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: 5906e55f-7d54-4d5d-8a43-57f779b3435c

	measure 'Atendido BÚSSOLA' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "BÚSSOLA"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: 97ed73bc-36de-4b1f-be29-39f17132da45

	measure 'Atendido COMPRAS' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "COMPRAS"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: b0aa552e-8bcd-461d-a380-3a02fb84db6e

	measure 'Atendido FIDELIZA+' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "FIDELIZA+"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: 821e4287-5dda-4938-8d6e-7e2fd6425fb2

	measure 'Atendido PAI' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "PAI"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: c2571e77-40db-416f-8ccd-99ca1ac72c7f

	measure 'Atendido PBM' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "PBM"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: 9aac3ed1-b4ea-456d-bce4-0088ccbc6191

	measure 'Atendido PEC' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "PEC"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: 21124405-1630-4d8c-99d7-c4f8288039fe

	measure 'Atendido RAIO-X' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "RAIO-X"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: 3a9605ae-6507-46c9-85b9-b322f89b6422

	measure 'Atendido TRADE' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "TRADE"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: c22fa01a-730d-43ac-9036-c480fa3f1c9b

	measure 'Atendido Comp. Preço' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[nome] = "COMPARADOR DE PREÇOS"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Outros
		lineageTag: 6a822e29-4128-484b-8fa4-f2b02ea1e4eb

	measure 'Atendido E-Delivery' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[nome] = "E-DELIVERY"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Outros
		lineageTag: b4b225bf-b362-4685-bb33-ea9a9b6f571d

	measure 'Atendido GC' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[nome] = "GC"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Outros
		lineageTag: 4a9d81f8-fe00-4174-8856-d1481529cda8

	measure 'Atendido Minha Saúde' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[nome] = "MINHA SAÚDE"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Outros
		lineageTag: e5a7fe6c-345e-4c47-8276-4bf901a31809

	measure 'Atendido Orion' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[nome] = "ORION"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Outros
		lineageTag: 66aa865d-2371-46f3-a803-77f10959b5de

	measure 'Atendido Scantech' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[nome] = "SCANTECH"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Outros
		lineageTag: 4933e452-7994-4008-9713-5c740c75ce5d

	measure 'Razão Social' =
			
			
			VAR Loja = DISTINCTCOUNT(dimLoja[LOJA])
			
			RETURN IF(Loja>1, "-", SELECTEDVALUE(dimLoja[RAZAOSOCIAL]))
		displayFolder: Sobre a Loja
		lineageTag: eeba55d6-0e08-4298-ba44-6ad65581e40f

	measure 'Nome Fantasia' =
			
			
			VAR Loja = DISTINCTCOUNT(dimLoja[LOJA])
			
			RETURN IF(Loja>1, "-", SELECTEDVALUE(dimLoja[FANTASIA]))
		displayFolder: Sobre a Loja
		lineageTag: 93893650-76d4-448c-bfd7-5093746354c4

	measure Telefone =
			
			
			VAR Loja = DISTINCTCOUNT(dimLoja[LOJA])
			
			RETURN IF(Loja>1, "-", SELECTEDVALUE(dimLoja[TELEFONE_MOVEL]))
		displayFolder: Sobre a Loja
		lineageTag: fcef4bf6-4fb0-4cbb-a0f5-986b866680b0

	measure 'D+ Desde' =
			
			
			VAR Loja = DISTINCTCOUNT(dimLoja[LOJA])
			
			RETURN IF(Loja>1, "-", SELECTEDVALUE(dimLoja[DATA_ASSOCIACAO]))
		formatString: Short Date
		displayFolder: Sobre a Loja
		lineageTag: 2e484263-5b21-4ead-b9e5-a1ce87f097da

		annotation PBI_FormatHint = {"isCustom":true}

	measure Cidade =
			
			
			VAR Loja = DISTINCTCOUNT(dimLoja[LOJA])
			
			RETURN IF(Loja>1, "-", SELECTEDVALUE(dimCidades[Name]))
		displayFolder: Sobre a Loja
		lineageTag: b85ef8f0-ca59-441c-918a-aa3c3a30ba96

	measure Clusters = ```
			
			
			VAR Lojas = DISTINCTCOUNT(dimLoja[LOJA_NUMERO])
			
			RETURN
			    IF(Lojas = 1,
			        SWITCH(
			            True,
			            MAX(dimLoja[CLUSTER]) = 1, "https://i.ibb.co/j9Yx0C83/numero-1.png", 
			            MAX(dimLoja[CLUSTER]) = 2, "https://i.ibb.co/jkZ3nZvw/numero-2.png",
			            MAX(dimLoja[CLUSTER]) = 3, "https://i.ibb.co/8DJgCR38/numero-3.png",
			            MAX(dimLoja[CLUSTER]) = 4, "https://i.ibb.co/FbPvtHKc/numero-4.png",
			            MAX(dimLoja[CLUSTER]) = 5, "https://i.ibb.co/27c4pf85/numero-5.png",
			            "https://i.ibb.co/chcFX5qF/zero.png"        
			        ),
			    "https://i.ibb.co/chcFX5qF/zero.png")
			```
		displayFolder: Geral
		lineageTag: 7809777d-5676-4680-b093-360af8ea5e99
		dataCategory: ImageUrl

	measure 'Atendido CESTAO' =
			
			
			VAR X = COALESCE(CALCULATE(COUNT(fatTarefa[id]), fatTarefa[fase_nome] = "CESTÃO"),0)
			VAR Loja = DISTINCTCOUNT(fatTarefa[LOJA])
			
			RETURN  IF(Loja>1, "https://i.ibb.co/wF985sZ7/excluir.png",
			            IF(X>0, "https://i.ibb.co/8DTr3BKj/verificar.png", "https://i.ibb.co/k6SzvzBQ/botao-x.png"))
		displayFolder: Serviços Realizados
		lineageTag: d4319b97-531f-4f8a-a68c-c8cbdfce2250

	measure 'Qtd. Serviços recorrentes exitentes' = ```
			
			    CALCULATE(
			        DISTINCTCOUNT(fatTarefa[fase_nome]),
			        FILTER(
			            ALL(fatTarefa),
			            fatTarefa[fase_nome] <> "NOVO LAYOUT"
			    )
			    )
			```
		formatString: 0
		displayFolder: Serviços
		lineageTag: b1b80328-fa14-4f10-9a81-98a16840fb7b

	measure 'Qtd. serviços recorrentes realizados' = ```
			
			
			VAR Loja = SELECTEDVALUE(fatTarefa[Loja_Numero])
			
			RETURN    
			    COALESCE(
			        CALCULATE(
			            DISTINCTCOUNT(fatTarefa[fase_nome]),
			            FILTER(
			                ALL(fatTarefa),
			                fatTarefa[Loja_Numero] = Loja &&
			                fatTarefa[fase_nome] <> "NOVO LAYOUT"
			            )
			        ),
			    0)
			
			```
		formatString: 0
		displayFolder: Serviços
		lineageTag: 608f6df3-4a74-4e70-b170-f13593491467

	measure 'Total de Lojas Inauguradas' = CALCULATE(DISTINCTCOUNT(dimLoja[LOJA]), dimLoja[INAUGURADA])
		formatString: 0
		displayFolder: Geral
		lineageTag: 9e72661f-e18a-4b16-aece-69661b26c581

	measure 'Qtd. Totas Tarefas' = DISTINCTCOUNT(fatTarefa[id])
		formatString: 0
		displayFolder: Serviços
		lineageTag: a42a9f0b-b297-4201-bee5-a139c2d3c69f

	measure 'Qtd. Tarefas CT' = ```
			
			COALESCE(
			    CALCULATE(
			        DISTINCTCOUNT(fatTarefa[id]),
			        fatTarefa[nome] IN { "CADUCIDADE", "TENTATIVA" }
			    ),
			    0
			)
			
			```
		formatString: 0
		displayFolder: Serviços
		lineageTag: 71e6fe07-c6e5-4954-8fc3-47e50152abd6

	measure 'Qtd. Dias' = COALESCE(CALCULATE(DISTINCTCOUNT('dimCalendario SULTS'[Date]), 'dimCalendario SULTS'[Dia da semana] <> "dom", 'dimCalendario SULTS'[Dia da semana] <> "sáb"),0)
		formatString: 0
		displayFolder: Serviços
		lineageTag: f1afc8ee-4019-4489-b5a1-b97da19d390b

	measure 'Qtd. Responsaveis' = COALESCE(DISTINCTCOUNT(fatTarefa[responsavel_nome]),0)
		formatString: 0
		displayFolder: Serviços
		lineageTag: 4d96fcc6-6103-46e9-90cd-12689680a8fa

	measure 'Média de Atendimento por Dia e Resp.' = COALESCE(DIVIDE(DIVIDE([Qtd. Atendimentos], [Qtd. Dias],0),[Qtd. Responsaveis],0),0)
		formatString: 0.0
		displayFolder: Serviços
		lineageTag: 30718a4c-8e6f-4411-b7a9-b6c16abf44a3

	measure 'Qtd atendimentos' = DISTINCTCOUNT(fatAtendimentos[chave_id])
		formatString: 0
		displayFolder: Focal
		lineageTag: 612e03af-11d9-4570-9107-54fa6dd90c45

	measure 'Qtd responsável' = DISTINCTCOUNT(fatAtendimentos[responsavel])
		formatString: 0
		displayFolder: Focal
		lineageTag: 4d519972-d296-4d62-a687-a7e64e01573f

	measure 'Qtd lojas' = DISTINCTCOUNT(fatAtendimentos[loja])
		formatString: 0
		displayFolder: Focal
		lineageTag: 9513f485-a9f4-4c89-9eb1-98d2cce16210

	measure 'Qtd tarefas' = DISTINCTCOUNT(fatAtendimentos[tarefa])
		formatString: 0
		displayFolder: Focal
		lineageTag: 2032edb1-93f0-475b-a4e3-561f6e0ee326

	measure 'Qtd dias' = COALESCE(CALCULATE(DISTINCTCOUNT('dimCalendario SULTS'[Date]), 'dimCalendario SULTS'[Dia da semana] <> "dom", 'dimCalendario SULTS'[Dia da semana] <> "sáb"),0)
		formatString: 0
		displayFolder: Focal
		lineageTag: ffc7d8f5-1870-403e-b4e4-090e5b3904f6

	measure 'Media de Atendimentos por Loja' = DIVIDE([Qtd atendimentos], [Qtd lojas],0)
		displayFolder: Focal
		lineageTag: 944610d9-e2d8-417d-ba73-6d3b3f71f1f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media de Atendimentos por Responsável' = COALESCE(DIVIDE([Qtd atendimentos],[Qtd responsável], 0),0)
		displayFolder: Focal
		lineageTag: 688fab99-952c-46fc-916a-847f23bb2289

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media de Atendimentos por dia' = COALESCE(DIVIDE([Qtd atendimentos],[Qtd dias],0),0)
		displayFolder: Focal
		lineageTag: f7d7580f-939a-44bf-9ac6-b19ea5ad68e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media de Atendimento por Dia e Resp.' = COALESCE(DIVIDE(DIVIDE([Qtd atendimentos], [Qtd atendimentos],0),[Qtd responsável],0),0)
		displayFolder: Focal
		lineageTag: 7a684018-22a6-44fd-acb5-98a34cea3284

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Auditor =
			
			
			VAR NLojas = COUNT(dimLoja[LOJA_NUMERO])
			VAR Responsavel = SELECTEDVALUE(dimProjeto[responsavel_nome])
			RETURN IF(NLojas>1, "-", IF(ISBLANK(Responsavel), "Não Encontrado", Responsavel))
		lineageTag: b9fab78d-daed-45bf-a2c6-fe0d18ea11e7

	measure 'Assunto Cartão' = ```
			
			VAR AssuntoSelecionado = SELECTEDVALUE(fatAtendimentos[assunto])
			RETURN
			IF(
			    ISBLANK(AssuntoSelecionado), 
			    "Sem Assunto", 
			    AssuntoSelecionado
			)
			```
		displayFolder: Focal
		lineageTag: 43a61275-c793-4e4c-9ba8-29241e6074a4

	column Column
		isHidden
		formatString: 0
		lineageTag: 3cd963fd-05ed-4cf8-9bc9-e637566bdf76
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 39d220e0d266470c9dee36557b4f7fe2

