table Atualização
	lineageTag: f4484955-0c68-40a5-82c2-82dfe7e4b596

	measure 'Texto Última Att' = "|  ATUALIZADO EM: " & SELECTEDVALUE('Atualização'[Última Atualização])
		lineageTag: 8336bbd3-9473-476f-9406-1f04dab44555

	column 'Última Atualização'
		dataType: dateTime
		formatString: General Date
		lineageTag: c07aa36b-7edd-4f15-acca-d5af8f8964c2
		summarizeBy: none
		sourceColumn: Última Atualização

		variation Variation
			isDefault
			relationship: 3168bdbb-540e-4247-83f1-29211a3f49fe
			defaultHierarchy: LocalDateTable_88a8d2c4-0559-4718-88fd-1348b80b9a2b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Atualização = m
		mode: import
		source =
				let
				    Fonte = DateTimeZone.LocalNow(),
				    #"Convertido para Tabela" = #table(1, {{Fonte}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Última Atualização"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Última Atualização", type datetimezone}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

