table dimPessoa
	lineageTag: 2adfa28c-fcad-4c7e-bf75-4bf0b14f79ae

	column id_pessoa
		dataType: int64
		formatString: 0
		lineageTag: ae120069-96f2-477d-a878-0998e6959e87
		summarizeBy: sum
		sourceColumn: id_pessoa

		annotation SummarizationSetBy = Automatic

	column id_movidesk
		dataType: int64
		formatString: 0
		lineageTag: af790748-75af-4573-8093-438656302d27
		summarizeBy: sum
		sourceColumn: id_movidesk

		annotation SummarizationSetBy = Automatic

	column id_funcao
		dataType: string
		lineageTag: 5f5fc4cb-2584-470b-9bc3-ddefde0e0e80
		summarizeBy: none
		sourceColumn: id_funcao

		annotation SummarizationSetBy = Automatic

	column id_sults
		dataType: int64
		formatString: 0
		lineageTag: 7095f719-efb8-48b1-b0f6-e00036d7455a
		summarizeBy: sum
		sourceColumn: id_sults

		annotation SummarizationSetBy = Automatic

	column nome_oficial
		dataType: string
		lineageTag: d985e0a1-af3e-41ca-803c-38989e9ca111
		summarizeBy: none
		sourceColumn: nome_oficial

		annotation SummarizationSetBy = Automatic

	column departamento_nome
		dataType: string
		lineageTag: 6876b06e-7a97-4cf5-8daa-2cd2f6bf277e
		summarizeBy: none
		sourceColumn: departamento_nome

		annotation SummarizationSetBy = Automatic

	column departamento_id
		dataType: int64
		formatString: 0
		lineageTag: 97226ebe-d287-419b-bcdd-9e2a0f6bcc22
		summarizeBy: sum
		sourceColumn: departamento_id

		annotation SummarizationSetBy = Automatic

	column ativo
		dataType: int64
		formatString: 0
		lineageTag: c9859439-5646-4122-8980-7d3eecd446e0
		summarizeBy: sum
		sourceColumn: ativo

		annotation SummarizationSetBy = Automatic

	partition dimPessoa = m
		mode: import
		source =
				let
				    Fonte = Odbc.DataSource("dsn=dbSults", [HierarchicalNavigation=true]),
				    dbSults_Database = Fonte{[Name="dbSults",Kind="Database"]}[Data],
				    dim_responsaveis_Table = dbSults_Database{[Name="dim_pessoas",Kind="Table"]}[Data],
				    #"Colunas Renomeadas" = Table.RenameColumns(dim_responsaveis_Table,{{"nome_oficial", "nome_oficial"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

