table fatChamadoSults
	lineageTag: 542a2cab-b612-4b4e-baf4-954eeb3ed16f

	column id
		dataType: int64
		formatString: 0
		lineageTag: 481caf62-e237-43f4-b0f3-e4daa3a19672
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column titulo
		dataType: string
		lineageTag: 9962d6eb-7a5e-40da-bcfb-bf703ae7cadb
		summarizeBy: none
		sourceColumn: titulo

		annotation SummarizationSetBy = Automatic

	column resolvido
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4a58611-2b77-494c-bfb7-28275384ede1
		summarizeBy: none
		sourceColumn: resolvido

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column solicitante_id
		dataType: int64
		formatString: 0
		lineageTag: 3db605d7-94c7-44e3-b93b-3b5d9906e70b
		summarizeBy: sum
		sourceColumn: solicitante_id

		annotation SummarizationSetBy = Automatic

	column solicitante_nome
		dataType: string
		lineageTag: 91676a1d-9f09-4cfa-a228-45aa299965d7
		summarizeBy: none
		sourceColumn: solicitante_nome

		annotation SummarizationSetBy = Automatic

	column responsavel_id
		dataType: int64
		formatString: 0
		lineageTag: 687fab1c-7a4b-45a3-ba5a-67cb17067898
		summarizeBy: sum
		sourceColumn: responsavel_id

		annotation SummarizationSetBy = Automatic

	column responsavel_nome
		dataType: string
		lineageTag: c3d14715-afd5-46f0-beda-5c11e8ae8906
		summarizeBy: none
		sourceColumn: responsavel_nome

		annotation SummarizationSetBy = Automatic

	column departamento_id
		dataType: int64
		formatString: 0
		lineageTag: cb84736f-6866-4a18-9398-e762b07c8690
		summarizeBy: sum
		sourceColumn: departamento_id

		annotation SummarizationSetBy = Automatic

	column departamento_nome
		dataType: string
		lineageTag: e6b34dfc-735c-4cff-b175-03427263b75c
		summarizeBy: none
		sourceColumn: departamento_nome

		annotation SummarizationSetBy = Automatic

	column assunto_id
		dataType: int64
		formatString: 0
		lineageTag: da1adf15-36d3-42ff-ac94-688df249fd87
		summarizeBy: sum
		sourceColumn: assunto_id

		annotation SummarizationSetBy = Automatic

	column assunto_nome
		dataType: string
		lineageTag: fea0356a-b9e8-4597-a7b4-f120c22c5f69
		summarizeBy: none
		sourceColumn: assunto_nome

		annotation SummarizationSetBy = Automatic

	column NomeSolicitante =
			
			IF(
			    --58, 67 e 70 são os ids das pessoas do marketing da tabela dim_responsaveis no banco
			    fatChamadoSults[solicitante_id] IN {58, 67, 70},
			
			    -- Se o ID ESTIVER na lista, executa a sua fórmula que já funciona
			    LOOKUPVALUE(
			        dimPessoa[nome_oficial],
			        dimPessoa[id_sults],
			        fatChamadoSults[solicitante_id]
			    ),
			
			    -- Se o ID NÃO ESTIVER na lista, retorna "Outro"
			    "Outro"
			)
		lineageTag: 91cb2b81-70ff-4a92-a7bd-bbf818d2eb05
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NomeResponsavel =
			
			IF(
			    --IDs sults dos reponsaveis marketing
			    fatChamadoSults[responsavel_id] IN {58, 67, 70},
			
			    -- Se o ID está na lista, busca o nome ativando a relação INATIVA
			    LOOKUPVALUE(
			        dimPessoa[nome_oficial],
			        dimPessoa[id_sults],
			        fatChamadoSults[responsavel_id]
			    ),
			
			    -- Caso contrário, retorna "Outro"
			    "Outro"
			)
		lineageTag: 797568c1-fa6d-480b-a0d1-0bef200a3ae2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fatChamadoSults = m
		mode: import
		source =
				let
				    Fonte = Odbc.DataSource("dsn=dbSults", [HierarchicalNavigation=true]),
				    dbSults_Database = Fonte{[Name="dbSults",Kind="Database"]}[Data],
				    vw_prata_chamados_sults_View = dbSults_Database{[Name="vw_prata_chamados_sults",Kind="View"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(vw_prata_chamados_sults_View,{{"departamento_id", Int64.Type}, {"assunto_id", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

