table Navegacao
	lineageTag: d50b0130-3d2d-465f-b9a3-0e2c5fa411ab

	column Páginas
		dataType: string
		lineageTag: d7c14faf-0123-4074-8809-8539931937dd
		summarizeBy: none
		sourceColumn: Páginas

		annotation SummarizationSetBy = Automatic

	column Setor
		dataType: string
		lineageTag: 76ba6c96-c444-4864-b66b-3f248cb81218
		summarizeBy: none
		sourceColumn: Setor

		annotation SummarizationSetBy = Automatic

	partition Navegacao = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hY6xCsMwDER/pWjOT4R26ZAp2YwHE4tylEhgKf7+miZQKJhsx93TnUKgp2CF0kCLZjWKQ6Bxz3AtbM0d8waBeUmOqkfsLBkbi+vtRJEa+kDhQ/9R1zVTMksdzGz/Ll31zVwqVu08fVepLOjcTqm82SGvFv90jB8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t, #"Coluna 2" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}, {"Coluna 2", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Coluna 1", "Páginas"}, {"Coluna 2", "Setor"}})
				in
				    #"Colunas Renomeadas"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

