table Navegacao
	lineageTag: f0f6284a-7578-4786-b27b-e31c3e7d6962

	column Páginas
		dataType: string
		lineageTag: 1c065669-6675-4fd5-bdb0-0a803d63a56c
		summarizeBy: none
		sourceColumn: Páginas

		annotation SummarizationSetBy = Automatic

	column Setor
		dataType: string
		lineageTag: 98fe77eb-f6a0-4e9f-a9e4-7062c500d944
		summarizeBy: none
		sourceColumn: Setor

		annotation SummarizationSetBy = Automatic

	partition Navegacao = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hY0xCsAgDEWvUjJ7CencqaM4SA0lFBNIouevWyfp9uG9x08JYq/komgQINZGTOZanIZADhM7cqWG7LIQzPqE2694og66ZPGzCw9kWrRH0Qed+J742zm/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Páginas = _t, Setor = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Páginas", type text}, {"Setor", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

